### ISSUE TITLE
[SPIKE] - Qual lib de componentes headless é melhor?

### ISSUE THREAD

**Issue by salviotonon** [Mentor-Cycle/mentor-cycle-fe#10]
### Conforme a task no Trello **- [SPIKE] - Qual lib de componentes headless é melhor?**

1. Entender o que são componentes headless:  deixo a baixo um artigo que fiz sobre o tema para um esclarecimento sobre o assunto e comparação das possiveis opções que podemos usar no projeto

>Título = _Qual a melhor biblioteca de componentes headless: Reach UI, Primitives - Radix UI ou Headless UI? Análise com Next.js e Tailwind CSS_
https://www.linkedin.com/pulse/qual-melhor-biblioteca-de-componentes-headless-reach-ui-salvio-tonon

2. Pesquisar sobre as libs de componentes headless: A task específica menciona três libs de componentes headless: Reach UI, Radix UI e Headless UI. O objetivo é encontrar informações sobre essas libs e analisar seus pontos positivos e negativos. Uma tabela ponderada sobre cada especificidade que vamos precisar no projeto.

![Captura de tela 2023-02-15 220933](https://user-images.githubusercontent.com/110191259/219362558-81da5a69-275c-4ac8-8bac-d99f69d170b7.jpg)

3. Fazer uma análise das libs: Com base nas informações coletadas nas pesquisas:

![Captura de tela 2023-02-15 221311](https://user-images.githubusercontent.com/110191259/219364044-7b99aa41-5282-4891-a04b-d0fc3872d327.jpg)

Como sugestão para o projeto, meu voto vai para o Radix UI. Com base em uma análise comparativa entre três das principais bibliotecas de componentes headless, Reach UI, Headless UI e Radix UI, o Radix UI se destacou em diversos aspectos.

Uma das vantagens do Radix UI é a sua variedade de componentes, que cobrem desde elementos básicos, como botões e inputs, até componentes mais complexos, como modais e tooltips.

Outro ponto forte do Radix UI é a sua capacidade de personalização. Ele oferece um grande número de propriedades para cada componente, o que permite que você ajuste o estilo e o comportamento dos componentes de acordo com as necessidades do seu projeto. Além disso, o Radix UI é altamente extensível, permitindo que você crie seus próprios componentes personalizados com facilidade.

### Esta issue tem como objetivo a discussão para decidir qual biblioteca de componentes utilizar. Sinta-se à vontade para expressar suas opiniões e ideias, mesmo que elas sejam diferentes das que já foram apresentadas.

**Comment by oliveirabalsa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[SPIKE] - Qual lib de componentes headless é melhor?](https://trello.com/c/qzI1xzKI/65-spike-qual-lib-de-componentes-headless-%C3%A9-melhor)

**Comment by thiagopuntar** [comment]
Excelente trabalho como sempre Salvio. Concordo com sua decisão de utilizarmos Radix UI. Vamos em frente.
