### ISSUE TITLE
Erro ao Logar com o linkedin

### ISSUE THREAD

**Issue by JoaoVictor531** [Mentor-Cycle/mentor-cycle-fe#117]
Dado que eu esteja na tela de login
Quando eu clico no botão "Entrar com o Linkedin", me autentico e permito a utilização de meus dados
Então é aberta uma guia com a tela preta, exibindo uma mensagem de erro.

Imagem 01
> ![image](https://user-images.githubusercontent.com/109318209/236953320-aab690af-7d4f-475b-8690-925abbe0f4de.png)
 
Imagem 02
> ![image](https://user-images.githubusercontent.com/109318209/236953245-c5ce2789-ca1c-456c-abcd-f204ed55f82b.png)

Imagem 03
> ![image](https://user-images.githubusercontent.com/109318209/236953259-6ae1d697-4380-44cb-ba5f-b0dd955076fa.png)

Obs imagem 02: link de redirecionamento da mensagem leva a uma pagina branca

> 
![image](https://user-images.githubusercontent.com/109318209/236954368-f9e5d1b5-e0c7-49cb-8161-85f4ecab1adc.png)

![image](https://user-images.githubusercontent.com/109318209/236954396-06318ec6-00e1-4d9e-8f5d-b56efacbaed2.png)

**Comment by oliveirabalsa** [comment]
@JoaoVictor531 existe um card de documentação alertando sobre o login com mídias sociais, mas irei dar 3 pontos pelo teste, obrigado!
