### ISSUE TITLE
Erro ao Loogar com o Google

### ISSUE THREAD

**Issue by JoaoVictor531** [Mentor-Cycle/mentor-cycle-fe#118]
Dado que eu esteja na tela de login
Quando eu clico no botão "Entrar com o Google"
Então é exibido uma mensagem informativa

Imagem 01
> ![image](https://user-images.githubusercontent.com/109318209/236955077-8aac7ba9-b7f0-4737-ada1-739f5df29f60.png)

Imagem 02
> 
![image](https://user-images.githubusercontent.com/109318209/236955165-a6e67a7b-af46-4a66-a72c-f5e4606bc688.png)

**Comment by oliveirabalsa** [comment]
@JoaoVictor531 existe um card de documentação alertando sobre o login com mídias sociais, mas irei dar 3 pontos pelo teste, obrigado!
