### ISSUE TITLE
Termos de Uso, Política de Privacidade e Cookies

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#122]
Ter opção para o usuário NÃO CONCORDAR e CONFIGURAR o que ele deseja liberar.

![image](https://user-images.githubusercontent.com/18746557/236959467-b300aaad-d493-4c13-b3c1-4a5a0a4f518c.png)

**Comment by oliveirabalsa** [comment]
@adsguilherme no momento optamos por essa abordagem, pois para utilizar a plataforma ele precisa acertar com esses termos, caso contrario não poderá, pois isso implica em coisas que no momento a plataforma não abordou no MVP, porém essa mensagem será alterada para um pequeno texto abaixo do botão de entrar. Irei colocar 3 pelo teste

**Comment by salviotonon** [comment]
aguardando alteração no figma
