### ISSUE TITLE
Ordenação da lista de mentores

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#123]
Qual é a ordenação que a aplicação faz para apresentar os mentores na listagem ?

![image](https://user-images.githubusercontent.com/18746557/236960541-49d1a181-5af3-4a21-bd86-d094388cc15f.png)

Na request informa que é :

order: "ASC"
orderBy: "firstName"

![image](https://user-images.githubusercontent.com/18746557/236962159-2b0f3357-ae80-4baf-b41b-0754ada9db0d.png)

**Comment by oliveirabalsa** [comment]
Boa, creio que isso deveria ser em desc

**Comment by adsguilherme** [comment]
Essa ai vai valer pontuação, correto ?
