### ISSUE TITLE
Profile: Digite seu País/Estado aqui

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#128]
Ao informar País/Estado no perfil, essa informação não é apresentada na tela de /profile. 

No entanto depois validando notei que essa informação vem do cadastro do usuário. Mas mesmo informando o País e não selecionando o Estado, a regra de negócio renderiza pelo visto quando informado os 2. Poderia então mudar para que o estado seja um valor required, para não termos esse comportamento e dúvida ao usuário de qual valor vem setado. E neste caso, visto que no cadastro já temos esse valor de PAÍS/UF, poderia remover então da edição de perfil essa opção, não tornando redudante essa informação. 

![image](https://user-images.githubusercontent.com/18746557/236971427-83dcad68-f39c-49f8-874d-2ac5ed39a83f.png)
![image](https://user-images.githubusercontent.com/18746557/236971434-cbdeea50-7386-4507-bbaf-530c0b0b9a28.png)

**Comment by oliveirabalsa** [comment]
Essa edição não é redundante devido a se o usuário fizer login com mídias sociais nenhuma delas nos informa isso, e consequentemente ele poderá atualizar via edição, poderia descrever melhor o problema na atualização, por favor?

**Comment by adsguilherme** [comment]
@oliveirabalsa 
Explicando: Ao entrar na edição do perfil o campo PAÍS/ESTADO não remete ao dados que vemos na tela /profile. Se obervar o print 1 foi informado BRASIL/ACRE, porém no print 2 está sem essa informação, apenas o texto Digite seu País/Estado. E justamente esse dado do /profile vem do fluxo de CADASTRO.

E o campo PAÍS/ESTADO da edição de perfil reflete no card de mentores.

Ou seja, como no cadastro o campo ESTADO não é required, se não preencher ele acaba também não trazendo o dado do país. Então como solução, essa edição do perfil deveria tambpem refletir nessa tela do /profile.
