### ISSUE TITLE
Mentorado realizando acesso ao perfil de um Mentor

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#132]
Na visão de Mentorado ao ver o perfil de um Mentor, poderia ser melhorada essa parte das informações.

![image](https://user-images.githubusercontent.com/18746557/236974706-89cf335a-b32b-4d79-abc3-22ffc10d750b.png)

**Comment by oliveirabalsa** [comment]
Boa, para quem for executar, temos que adicionar os placeholders aqui também já existe na tela de editar perfil
