### ISSUE TITLE
Filtro Dashboard retorna 'Você não possui nenhuma mentoria agendada' mesmo possuindo agendamento

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#134]
Foi realizado um agendamento de mentoria e ao utilizar o filtro mudando para o status 'A Confirmar' apresenta a mensagem: 'Você não possui nenhuma mentoria agendada', no entanto existe uma mentoria para: Quarta-Feira Você tem 1 mentoria(s) marcada(s) para o dia 10/05/2023 - 13:30 (agendada).

![image](https://user-images.githubusercontent.com/18746557/236975358-8af75759-aa17-4c2a-8e82-e73d38a5f279.png)

Ocorre o mesmo comportamento por parte do mentorado:

![image](https://user-images.githubusercontent.com/18746557/236975871-dc5d6d00-0e98-49b2-8860-389883e81d38.png)

**Comment by oliveirabalsa** [comment]
O real problema é que provavelmente você tem uma mentoria agendada porém só consegue ver como mentorado e não menor, para quem for executar essa issue o correto é: Remover o "mentorias agendadas" caso você tenha mentorias não sendo um mentor, porém com o perfil de mentor ativo.
