### ISSUE TITLE
Undefined na página /mentors

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#137]
Ao acessar o perfil de qualquer Mentor e dar um F5, a página carrega um undefinied.

Está retornando um erro 400 na api, avaliar se isso tem relação com o undefined.

https://mentor-cycle-fe-dev.up.railway.app/mentors/141f47b1-0046-4d3d-be48-325215a4c43c

![image](https://user-images.githubusercontent.com/18746557/236992597-569db5d9-6063-4d56-8307-c64356ce08e2.png)
![image](https://user-images.githubusercontent.com/18746557/236992616-77ce618f-2744-4d26-af11-bc4ac3f12839.png)
![image](https://user-images.githubusercontent.com/18746557/236992624-c9a46ae8-47a1-4364-b53d-ea8652f6303a.png)

**Comment by oliveirabalsa** [comment]
Validando aqui o undefined permanece enquanto a API esta fazendo a request, portanto precisamos colocar um Loading nessa tela durante a request,
