### ISSUE TITLE
Load no select das especialidades

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#139]
Ao carregar a página o select das especialidades apresenta um load.
Sugestão: remover isso do componente

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/88d6ba48-9369-41f4-98ee-9728b5c2812e)

**Comment by oliveirabalsa** [comment]
@adsguilherme creio que o usuário precisa de um feedback para o carregamento, uma vez que se entrar na página e as especialidades não carregarem, irá aparecer um select vazio, creio que um comportamento seria desabilitar o componente enquanto carrega, mas não sei em termos de UX isso, irei pontuar com 3

**Comment by salviotonon** [comment]
como é necessario fazer uma requisição para o back end para buscar as especialidades, é necessario ter um loading. até a equipe de ui/ux decidir alguma melhoria, mudei a logica para o input ficar desabilitado até a requisição estar completa.
