### ISSUE TITLE
Cadastro de usuário via API passando dados não esperados no front

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#143]
Está permitindo cadastrar "skills" inexistentes e isso reflete no frontend.

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/77e7c943-4dc7-40d9-911f-2cc48423810a)
![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/b51961f2-56b5-4096-aab5-ae73e924f667)

**Comment by salviotonon** [comment]
Esse bug esta ocorrendo através do playground do graphQL. pelo input de especialidade do front coloquei uma validação adicional, issue para conversar com a equipe de back end
