### ISSUE TITLE
Gabriela-Silveira - QA / Funcionalidade de Login não funciona

### ISSUE THREAD

**Issue by Gabriela-Silveira** [Mentor-Cycle/mentor-cycle-fe#144]
Funcionalidade: Fazer login através do LinkedIn

-Ao tentar fazer login com o LinkedIn, aparece o erro **"{"statusCode":500,"message":"Internal server error"}"**.

https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/108082488/52b01147-aa87-418b-8163-189959662707

**Comment by oliveirabalsa** [comment]
Olá @Gabriela-Silveira irei dar 3 pontos pelo teste, ja temos uma issue de documentação falando sobre: https://github.com/Mentor-Cycle/mentor-cycle-fe/issues/107
