### ISSUE TITLE
Gabriela-Silveira - Acesso inválido

### ISSUE THREAD

**Issue by Gabriela-Silveira** [Mentor-Cycle/mentor-cycle-fe#145]
Funcionalidade: Entrar com uma conta do google.

-Não é possível fazer login com uma conta do google.

![Captura de tela 2023-05-09 204641](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/108082488/b68493f2-1c93-4b30-8ae9-465370629438)

**Comment by oliveirabalsa** [comment]
Olá @Gabriela-Silveira irei dar 3 pontos pelo teste, ja temos uma issue de documentação falando sobre: https://github.com/Mentor-Cycle/mentor-cycle-fe/issues/107
