### ISSUE TITLE
Filtro de status da mentoria

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#148]
Os filtros 'A Confirmar' e 'Realizada' não consegui simular na aplicação. Temos alguma feature que irá integrar com esses 2 filtros ?

Realizei o fluxo de 'Acessar Chamada', porém não apresentou nada sobre a mentoria ficar como 'Realizada'. 

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/43a4d1be-f716-4452-a85f-fb7a1b74e481)

**Comment by oliveirabalsa** [comment]
A quem for executar, remover essas opções.
