### ISSUE TITLE
Implementar na edição do perfil campo de especialização

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#150]
Quando realizado o cadastro podemos selecionar a especialização, no entanto depois do usuário cadastrado não temos um local para editar essa informação.

Sugestão: Implementar esse recurso na tela de edição de perfil, podendo reaproveitar o mesmo componente do cadastro.

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/090692f2-3d78-48b2-ae18-b9b65baa8743)
![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/ce57b218-fc69-4d64-a8fb-71b161b8fda1)
![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/42e16228-8145-4b07-8e62-c6bfbfa6574d)

**Comment by salviotonon** [comment]
Aguardando a opinião da equipe de ui/ux, deixarei com a label marcada para organização
