### ISSUE TITLE
Cadastro como mentorado

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#151]
Faz sentido ter a opção de Especialização para o cadastro de mentorado ?

Sugestão 1: Quando selecioando opção de cadastro 'Mentorado' remover o required do campo especialização. 
Sugestão 2: Remover essa opção.

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/8b6cde08-d288-4d86-82cb-826afd9d5927)

**Comment by oliveirabalsa** [comment]
Creio que sim, mas alterando o nome, especialização do mentor seria basicamente o ramo que atua e pro mentorado o que ele deseja aprender, teria que ver com o time de UI/UX
