### ISSUE TITLE
Apresentar mesmo nome em ambos locais da aplicação

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#152]
Sugestão: Apresentar no card de mentores, nome + sobrenome conforme página home.

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/c5985225-1c3c-43bc-a336-8c41bd0ef583)
![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/1ff3e6ee-5f7a-4104-bbc0-09cf9cc1694b)

**Comment by oliveirabalsa** [comment]
Hoje buscamos por firstname, o backend armazena os nomes separadamente, então creio que para filtrar full name, só se houvesse uma conversão via front-end, fica para analise

**Comment by salviotonon** [comment]
aguardando equipe de ui/ux, definir isso

**Comment by salviotonon** [comment]
alterado para full name nos card da pagina mentors
