### ISSUE TITLE
Bruno Henrique - Tester -  Login Linkedin: status 500

### ISSUE THREAD

**Issue by BrunoHsQA** [Mentor-Cycle/mentor-cycle-fe#154]
Erro ao escolher logar pelo linkedin: status 500
O usuário gosta de conveniência, por isso a maioria dos sites colocam a opção de logar por redes sociais, para que não precisam colocar todos os dados novamente.

Passo 1: Entrar no site "https://mentor-cycle-fe-dev.up.railway.app"
Passo 2: Clicar em "Entrar no Linkedin"
Passo 3: Colocar seu E-mail e senha do linkedin
Passo 4: Clicar em "Permitir"

![cycle-1link](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/97351783/9e3cf076-39f7-4623-bd24-4bf63deed467)
![cycle-2ink](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/97351783/1939561f-8fab-4175-a877-93b5e04b8e1d)
![cycle-3link](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/97351783/14b13db9-7ffc-4fd1-a14c-378c1ed049be)

Para uma melhor experiência do usuário, é importante que as funcionalidades que o site mostra estejam funcionais, mostrando que o mesmo está comprometido a dar ao internauta uma fluidez na navegação.

**Comment by oliveirabalsa** [comment]
Já há uma issue de documentação falando sobre isso mas darei 3 pontos pelo teste
