### ISSUE TITLE
Cadastro como mentor não funcionando

### ISSUE THREAD

**Issue by oliveirabalsa** [Mentor-Cycle/mentor-cycle-fe#156]
![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/57500163/cae7c76f-2587-4867-9c65-07f81d7836cb)

Foi efetuado o cadastro como mentor mas mesmo assim está considerando mentorado.

**Comment by adsguilherme** [comment]
@oliveirabalsa talvez esse caso deve estar ocorrendo por algum motivo. Realizando aqui o cadastro do dia 08/05 até hoje esse comportamento não ocorre. 

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/f3a5a435-d9ff-4ba1-acfd-84ba98c69560)
