### ISSUE TITLE
Luiza Mioli /QA - Cadastro linkedin 

### ISSUE THREAD

**Issue by luizamioli** [Mentor-Cycle/mentor-cycle-fe#157]
O sistema deixa o usuário entrar com o linkedin mesmo não estando cadastrado e não é direcionado para uma página onde aparece a informação que ele não é cadastrado, apenas aparece uma mensagem de erro.
![Uploading Captura de tela 2023-05-10 183344.png…]()

![Captura de tela 2023-05-10 183230](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/85746699/4b956ba6-3fb1-4f8e-894b-c87c6e505d8d)

Porque isso é um problema:

-O sistema deveria deixar o usuário entrar com o linkedin apenas se ele já estiver cadastrado e vinculado o linkedin a sua conta
-Mesmo se o usuário estivesse cadastrado, o login com o linkedin não estaria disponível 
-Muitas pessoas optam por esse login por ser mais rápido

Como reproduzir:
- entrar no link https://mentor-cycle-fe-dev.up.railway.app/ 
- clicar na opção "Entrar com linkedin" 
- realizar login com o linkedin

Eu direcionaria para uma página informando que o usuário ainda não tem cadastro (caso ele não tenha) e informaria na mesma, o link para criar o cadastro.

**Comment by oliveirabalsa** [comment]
Já há uma issue de documentação falando sobre isso mas darei 3 pontos pelo teste
