### ISSUE TITLE
Luiza Mioli / QA - Cadastro com o google

### ISSUE THREAD

**Issue by luizamioli** [Mentor-Cycle/mentor-cycle-fe#158]
Ao tentar logar com a conta do google, o sistema aparece a seguinte mensagem "Acesso bloqueado: a solicitação desse app é inválida"

- É um grande problema porque muitos usuários optam pelo login com google pois se torna mais rápido que os outros ou porque não lembra a senha.

Como reproduzir:
-Acessar o site https://mentor-cycle-fe-dev.up.railway.app/
-Clicar em "Entrar com google"
-Visualizar a mensagem em questão
![Captura de tela 2023-05-10 183659](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/85746699/a31d6947-5014-45f1-89f7-e661f373cac4)

**Comment by oliveirabalsa** [comment]
Já há uma issue de documentação falando sobre isso mas darei 3 pontos pelo teste
