### ISSUE TITLE
Luiza Mioli / QA - Campo "Especialização" falta área

### ISSUE THREAD

**Issue by luizamioli** [Mentor-Cycle/mentor-cycle-fe#160]
No cadastro de usuário, na parte de dados pessoais o campo "Especialização" não tem a opção QA/Tester.

Isso é um problema pois assim como eu, há outros usuários que são da área de qualidade e não conseguem realizar o cadastro corretamente.

Eu adicionaria a opção "QA" pois é uma área que sem dúvidas, irá participar do Mentor Cycle

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/85746699/a6c5d873-5eb1-4db1-9da4-e030efdd5ee1)

**Comment by salviotonon** [comment]
Conversar com a equipe de back end para adicionar na aplicação essa especialidade
