### ISSUE TITLE
Luiza / QA - Campo "Aniversário" no cadastro do usuário

### ISSUE THREAD

**Issue by luizamioli** [Mentor-Cycle/mentor-cycle-fe#162]
Cadastro não está funcionando quando cadastra uma data incorreta/sem data no campo "Nascimento".

Isso é um problema pois caso o usuário errar a data e não perceber, ao finalizar o cadastro o sistema vai ficar "carregando pra sempre" e ele não saberia o que fez de errado.

![Captura de tela 2023-05-10 190918](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/85746699/46c0f2eb-e31b-46c4-9aa9-362c24185034)

Eu adicionaria uma mensagem de erro no cadastro, informando qual erro é e voltando para etapa do erro do usuário, no caso "Dados pessoais". Também deixaria a data como um campo obrigatório.

![Captura de tela 2023-05-10 191628](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/85746699/dd7541be-7bd2-45c6-b90c-4bb86af0ea7e)

**Comment by salviotonon** [comment]
resolvido na PR https://github.com/Mentor-Cycle/mentor-cycle-fe/pull/167
