### ISSUE TITLE
Notificações:  perfil completo

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#164]
Mesmo com o perfil  completo, ao clicar em notificação mostra a opção Complete seu perfil.

Sugestão: Quando o perfil estiver completo, a notificação não deve conter esse informativo.

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/993429ef-1e44-4dbd-914c-06ec0c018c05)

**Comment by oliveirabalsa** [comment]
Checando no DB há algumas informações faltando 

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/57500163/190a4359-eb8d-47c9-bbc4-2fa338c967bb)
![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/57500163/98bbf0e9-4959-46f0-95ba-33320dea12d2)

**Comment by oliveirabalsa** [comment]
vou fechar essa se ainda tiver algo mais a acrescentar eu mudo o status

**Comment by adsguilherme** [comment]
@oliveirabalsa  Esse é o problema, CIDADE, GITHUB, LINKEDIN são informações da tela de CADASTRO. Não temos como editar isso no profile.

**Comment by salviotonon** [comment]
sugestão para ser levantada com a equipe de ui/ui
