### ISSUE TITLE
Reset your password - Footer email

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#168]
Ajuste do texto do footer do email, não está com uma boa formatação. 

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/aa210231-5b9d-44d8-a518-1e4761295763)

**Comment by oliveirabalsa** [comment]
Existe uma pasta no front chamada email o back importa de lá os templates, task Frontend
