### ISSUE TITLE
Reset your password - Informações ao usuário

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#169]
Ao realizar o fluxo de alteração de senha, e se não atender a regra definida rertorna um alert ao usuário: Não foi possivel alterar sua senha.

Na tela de CADASTRO tem um informativo de como deve ser o padrão de senha dentro da aplicação. 
_Sugestão_: Deixar esse padrão nessa tela de confirmação de senha.

**Observação**

Aqui o back end retorna:  
[0] "email must be an email"
[1] "Password should have symbols, numbers and uppercase characters"

Na tela de cadastro não informa que deve ter símbolos, apenas letra e números. Também não informa se deve conter upper case.
_Sugestão:_ 
1. Validar como vai ser o padrão de senha (se vai ser apenas letras e números ou se terá caracteres e letra com uppercase).
2. Remover do back essa validação "email must be an email".

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/c4f1fdc3-d833-4e81-b373-885a1d0bfc07)

**Comment by oliveirabalsa** [comment]
Poderia mandar o email dessa conta também?

**Comment by oliveirabalsa** [comment]
Essa rota deve mandar um email pro backend, provavelmente vc verá no payload, por isso não faz sentido remover a validação só back

**Comment by adsguilherme** [comment]
@oliveirabalsa 

ti.gscode+102@gmail.com

email=ti.gscode+101@gmail.com&pin=3508
