### ISSUE TITLE
Reset your password - Informada senha conforme o padrão

### ISSUE THREAD

**Issue by adsguilherme** [Mentor-Cycle/mentor-cycle-fe#170]
Informando a senha conforme o padrão definido no back 8QW%Y&Oh6vae, a aplicação retorna status code 400.

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/4c34b170-dd97-4def-b87a-c9e6b0241ced)
![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/18746557/609d2efc-4e34-42fb-acd1-41ebc3a2bfbf)

**Comment by oliveirabalsa** [comment]
Poderia mandar o email do qual vc tentou alterar a senha?

**Comment by adsguilherme** [comment]
@oliveirabalsa email:

ti.gscode+102@gmail.com

email=ti.gscode+101@gmail.com&pin=3508
