### ISSUE TITLE
[Front-end] - Cards de mentorias agendadas

### ISSUE THREAD

**Issue by naraoliveiraa** [Mentor-Cycle/mentor-cycle-fe#207]
O espaçamento entre os cards está como spacing between, resultando em um espaço muito grande entre os cards. É preciso ajustar a distribuição para packed / fixo alinhados à esquerda.

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/135335250/a457024c-ddbd-46c4-afb6-0c2411996e55)

**Comment by iannak** [comment]
vou fazer essa **OK**

**Comment by iannak** [comment]
@oliveirabalsa depois puxa pra mim por gentileza

**Comment by iannak** [comment]
finalizada PR #222
