### ISSUE TITLE
[Front-end] - Alteração de texto no dark mode

### ISSUE THREAD

**Issue by naraoliveiraa** [Mentor-Cycle/mentor-cycle-fe#208]
Quando o usuário altera o tema do site para o dark mode, o texto exibido no dropdown ainda permanece como "Dark Mode" em vez de ser atualizado para "Light Mode".

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/135335250/d9473702-79f5-46c3-8d8d-92324bec8df5)

**Comment by iannak** [comment]
fazendo essa :)

**Comment by iannak** [comment]
@oliveirabalsa sabe me dizer onde fica isso no código? que eu tentei achar, onde foi configurado o dark mode, e não achei

**Comment by salviotonon** [comment]
No componente Header, procura por menuOptions

**Comment by iannak** [comment]
valeu @salviotonon

**Comment by iannak** [comment]
#230 finalizado
