### ISSUE TITLE
[Front-end] - Redimensionar pop-up de agendamento

### ISSUE THREAD

**Issue by naraoliveiraa** [Mentor-Cycle/mentor-cycle-fe#213]
Os steps na etapa 2 do agendamento estão muito próximos uns dos outros.
![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/135335250/7a234b55-467c-469f-a9bd-39deaeab80e4)

É necessário aumentar a caixa do pop-up para que os steps tenham o mesmo tamanho da etapa anterior.
![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/135335250/8321f499-ee53-45b2-9aad-611b51b0a867)

**Comment by FelipePEduardo** [comment]
Vou pegar essa

**Comment by FelipePEduardo** [comment]
Vou pegar esse
