### ISSUE TITLE
[Front-end] - Pop-up de confirmação de mudança de foto

### ISSUE THREAD

**Issue by naraoliveiraa** [Mentor-Cycle/mentor-cycle-fe#214]
O texto do pop-up de confirmação de mudança de foto está com tamanho grande. É preciso reduzir tamanho da fonte.

![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/135335250/ed37e88c-ae38-4373-9210-fa87b5da416a)

**Comment by Ar3secchim** [comment]
Bom dia. 
Sou Renara, nova voluntária.  
Estou animada em poder  contribuir para a equipe como desenvolvedora front-end, estou iniciando minha carreira porém estou disposta a investir tempo e esforço para aprimorar minhas habilidades, principelmente em tecnologias que não domino.


Vou ficar responsável por essas tasks.
