### ISSUE TITLE
[Front-end] Refatorar section: de como funciona na Landing Page

### ISSUE THREAD

**Issue by Ar3secchim** [Mentor-Cycle/mentor-cycle-fe#276]
## 📊 Descrição 
 
Um erro na responsividadde, breakpoint está em 1536px e tinha que ser nos 1024px. 

![My project-1](https://github.com/Ar3secchim/project-77-days/assets/82913620/cc3494b4-9318-4587-8f1e-bf46b163e87e)

### 🛠️ Tasks a serem realizadas
- [ ]  realizar a mudança do breakpoint para a resposividade ficar de acordo com cada dispositivo.

**Comment by oliveirabalsa** [comment]
Boa @Ar3secchim !!!!
